AWSTemplateFormatVersion: '2010-09-09'
Description: Despliegue Final Alumno D - Servidor Migui en España (eu-south-2)

Parameters:
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Selecciona tu llave Llave_AlumnoD
    Default: Llave_AlumnoD

Resources:
  # 1. Security Group (Firewall)
  MiguiSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Acceso SSH, Web y NTP para Migui
      VpcId: vpc-0e4574e90bd362453
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: udp
          FromPort: 123
          ToPort: 123
          CidrIp: 172.31.0.0/16

  # 2. Instancia EC2
  MiguiWebServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      # AMI confirmada por el usuario en la captura
      ImageId: ami-048dc219ff68b99b1
      KeyName: !Ref KeyPairName
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: '0'
          SubnetId: subnet-0a37c560410204510
          GroupSet:
            - !Ref MiguiSecurityGroup
      Tags:
        - Key: Name
          Value: Webserver_Migui_D
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Instalacion automatica
          dnf update -y
          dnf install -y nginx mariadb105-server chrony
          systemctl enable --now nginx mariadb chronyd
          
          # Pagina web de bienvenida
          echo "<html><body style='font-family: Arial; text-align: center; padding-top: 50px;'> \
                <h1 style='color: #232F3E;'>Servidor Web de MIGUI - Alumno D</h1> \
                <p style='font-size: 1.2em;'>Desplegado correctamente en <b>España (eu-south-2)</b>.</p> \
                <div style='background: #f2f2f2; display: inline-block; padding: 20px; border-radius: 10px;'> \
                Infraestructura como Codigo con CloudFormation completa. \
                </div></body></html>" > /usr/share/nginx/html/index.html

Outputs:
  WebURL:
    Description: Haz clic aqui para ver tu web terminada
    Value: !Sub "http://${MiguiWebServer.PublicIp}"