server {
    listen 80;
    server_name _;

    location /profesores {
        proxy_pass http://127.0.0.1:5000/profesores;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_redirect off;
    }

    location /health {
        proxy_pass http://127.0.0.1:5000/health;
    }
}
